export const STEPS = [
  {
    id: 1,
    difficulty: 'Easy',
    layer: 'First Layer',
    title: 'White Cross',
    desc: "Start by forming a plus sign (+) on the white face. Match each edge piece's second color to the center of its adjacent face.",
    algorithms: [],
    tips: ["Always start with white — it's convention.", 'Hold the cube with white center on top.', "Don't worry about corners yet."],
  },
  {
    id: 2,
    difficulty: 'Easy',
    layer: 'First Layer',
    title: 'White Corners',
    desc: 'Insert the four corner pieces to complete the first layer.',
    algorithms: [{ notation: "R U R' U'", name: 'Right Trigger' }],
    tips: [],
  },
  {
    id: 3,
    difficulty: 'Medium',
    layer: 'Second Layer',
    title: 'Second Layer Edges',
    desc: 'Flip the cube so white is on the bottom. Insert middle-layer edge pieces.',
    algorithms: [
      { notation: "U R U' R' U' F' U F", name: 'Insert Right' },
      { notation: "U' L' U L U F U' F'", name: 'Insert Left' },
    ],
    tips: [],
  },
  {
    id: 4,
    difficulty: 'Medium',
    layer: 'Last Layer',
    title: 'Yellow Cross',
    desc: 'Form a yellow cross on the top face.',
    algorithms: [{ notation: "F R U R' U' F'", name: 'FRU' }],
    tips: [],
  },
  {
    id: 5,
    difficulty: 'Hard',
    layer: 'Last Layer',
    title: 'Yellow Face',
    desc: 'Orient all yellow corners so the entire top face is yellow.',
    algorithms: [{ notation: "R U R' U R U2 R'", name: 'Sune' }],
    tips: [],
  },
  {
    id: 6,
    difficulty: 'Hard',
    layer: 'Last Layer',
    title: 'Position Yellow Corners',
    desc: 'Move yellow corners to their correct positions.',
    algorithms: [{ notation: "U R U' L' U R' U' L", name: 'Corner Swap' }],
    tips: [],
  },
  {
    id: 7,
    difficulty: 'Hard',
    layer: 'Last Layer',
    title: 'Position Yellow Edges',
    desc: 'The final step! Cycle the last-layer edges into place.',
    algorithms: [
      { notation: "R U' R U R U R U' R' U' R2", name: 'CW Cycle' },
      { notation: "R2 U R U R' U' R' U' R' U R'", name: 'CCW Cycle' },
    ],
    tips: [],
  },
];

export const ALGORITHMS = [
  { step: 2, name: 'Right Trigger', notation: "R U R' U'", use: 'Insert white corners' },
  { step: 3, name: 'Insert Right', notation: "U R U' R' U' F' U F", use: 'Edge goes right' },
  { step: 3, name: 'Insert Left', notation: "U' L' U L U F U' F'", use: 'Edge goes left' },
  { step: 4, name: 'FRU', notation: "F R U R' U' F'", use: 'Yellow cross' },
  { step: 5, name: 'Sune', notation: "R U R' U R U2 R'", use: 'Orient yellow corners' },
  { step: 6, name: 'Corner Swap', notation: "U R U' L' U R' U' L", use: 'Position corners' },
  { step: 7, name: 'CW Cycle', notation: "R U' R U R U R U' R' U' R2", use: 'Cycle edges CW' },
  { step: 7, name: 'CCW Cycle', notation: "R2 U R U R' U' R' U' R'", use: 'Cycle edges CCW' },
];
